apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169684473
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169684473
    app.kubernetes.io/part-of: test-app-169684473
  name: java-quarkus-169684473
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169684473
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169684473
    spec:
      containers:
      - image: quay.io/hacdev/w4ewermk-tenant/test-app-169684473/java-quarkus-169684473@sha256:5c1009197fb47976b5b5525986475ca85df61a9fa16e5421cf00c7ee22b0d0d6
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
